# Generated by Django 4.0 on 2021-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.TextField(blank=True),
        ),
    ]
