# Generated by Django 4.0 on 2021-12-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image'),
        ('films', '0002_film_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFavoriteFilmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ManyToManyField(to='films.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
